# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:39:38+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class DfsSlatePlayer(BaseModel):
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerGameProjectionStatID: Optional[int] = None
    PlayerID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class Inning(BaseModel):
    AwayTeamRuns: Optional[int] = None
    GameID: Optional[int] = None
    HomeTeamRuns: Optional[int] = None
    InningID: Optional[int] = None
    InningNumber: Optional[int] = None


class News(BaseModel):
    Author: Optional[str] = None
    Categories: Optional[str] = None
    Content: Optional[str] = None
    NewsID: Optional[int] = None
    OriginalSource: Optional[str] = None
    OriginalSourceUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    PlayerID2: Optional[int] = None
    Source: Optional[str] = None
    Team: Optional[str] = None
    Team2: Optional[str] = None
    TeamID: Optional[int] = None
    TeamID2: Optional[int] = None
    TermsOfUse: Optional[str] = None
    TimeAgo: Optional[str] = None
    Title: Optional[str] = None
    Updated: Optional[str] = None
    Url: Optional[str] = None


class Player(BaseModel):
    BatHand: Optional[str] = None
    BirthCity: Optional[str] = None
    BirthCountry: Optional[str] = None
    BirthDate: Optional[str] = None
    BirthState: Optional[str] = None
    College: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    Experience: Optional[str] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FirstName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Height: Optional[int] = None
    HighSchool: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Jersey: Optional[int] = None
    LastName: Optional[str] = None
    MLBAMID: Optional[int] = None
    PhotoUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    ProDebut: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    Salary: Optional[int] = None
    SportRadarPlayerID: Optional[str] = None
    SportsDataID: Optional[str] = None
    SportsDirectPlayerID: Optional[int] = None
    StatsPlayerID: Optional[int] = None
    Status: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThrowHand: Optional[str] = None
    UpcomingGameID: Optional[int] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None
    XmlTeamPlayerID: Optional[int] = None
    YahooName: Optional[str] = None
    YahooPlayerID: Optional[int] = None


class PlayerGame(BaseModel):
    AtBats: Optional[float] = None
    BallsInPlay: Optional[float] = None
    BattingAverage: Optional[float] = None
    BattingAverageOnBallsInPlay: Optional[float] = None
    BattingOrder: Optional[int] = None
    BattingOrderConfirmed: Optional[bool] = None
    CaughtStealing: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DoublePlays: Optional[float] = None
    Doubles: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    EarnedRunAverage: Optional[float] = None
    Errors: Optional[float] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyDataSalary: Optional[int] = None
    FantasyDraftPosition: Optional[str] = None
    FantasyDraftSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsBatting: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsPitching: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldingIndependentPitching: Optional[float] = None
    FlyOuts: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    GrandSlams: Optional[float] = None
    GroundIntoDoublePlay: Optional[float] = None
    GroundOuts: Optional[float] = None
    HitByPitch: Optional[float] = None
    Hits: Optional[float] = None
    HomeOrAway: Optional[str] = None
    HomeRuns: Optional[float] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    InningsPitchedDecimal: Optional[float] = None
    InningsPitchedFull: Optional[float] = None
    InningsPitchedOuts: Optional[float] = None
    IntentionalWalks: Optional[float] = None
    IsGameOver: Optional[bool] = None
    IsolatedPower: Optional[float] = None
    LeftOnBase: Optional[float] = None
    LineOuts: Optional[float] = None
    Losses: Optional[float] = None
    Name: Optional[str] = None
    OnBasePercentage: Optional[float] = None
    OnBasePlusSlugging: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpponentPositionRank: Optional[int] = None
    OpponentRank: Optional[int] = None
    Outs: Optional[float] = None
    PitchesSeen: Optional[float] = None
    PitchesThrown: Optional[float] = None
    PitchesThrownStrikes: Optional[float] = None
    PitchingBallsInPlay: Optional[float] = None
    PitchingBattingAverageAgainst: Optional[float] = None
    PitchingBattingAverageOnBallsInPlay: Optional[float] = None
    PitchingBlownSaves: Optional[float] = None
    PitchingCatchersInterference: Optional[float] = None
    PitchingCompleteGames: Optional[float] = None
    PitchingDoublePlays: Optional[float] = None
    PitchingDoubles: Optional[float] = None
    PitchingEarnedRuns: Optional[float] = None
    PitchingFlyOuts: Optional[float] = None
    PitchingGrandSlams: Optional[float] = None
    PitchingGroundIntoDoublePlay: Optional[float] = None
    PitchingGroundOuts: Optional[float] = None
    PitchingHitByPitch: Optional[float] = None
    PitchingHits: Optional[float] = None
    PitchingHolds: Optional[float] = None
    PitchingHomeRuns: Optional[float] = None
    PitchingInningStarted: Optional[int] = None
    PitchingIntentionalWalks: Optional[float] = None
    PitchingLineOuts: Optional[float] = None
    PitchingNoHitters: Optional[float] = None
    PitchingOnBasePercentage: Optional[float] = None
    PitchingOnBasePlusSlugging: Optional[float] = None
    PitchingPerfectGames: Optional[float] = None
    PitchingPlateAppearances: Optional[float] = None
    PitchingPopOuts: Optional[float] = None
    PitchingQualityStarts: Optional[float] = None
    PitchingReachedOnError: Optional[float] = None
    PitchingRuns: Optional[float] = None
    PitchingSacrificeFlies: Optional[float] = None
    PitchingSacrifices: Optional[float] = None
    PitchingShutOuts: Optional[float] = None
    PitchingSingles: Optional[float] = None
    PitchingSluggingPercentage: Optional[float] = None
    PitchingStrikeouts: Optional[float] = None
    PitchingStrikeoutsPerNineInnings: Optional[float] = None
    PitchingTotalBases: Optional[float] = None
    PitchingTriples: Optional[float] = None
    PitchingWalks: Optional[float] = None
    PitchingWalksPerNineInnings: Optional[float] = None
    PitchingWeightedOnBasePercentage: Optional[float] = None
    PlateAppearances: Optional[float] = None
    PlayerID: Optional[int] = None
    PopOuts: Optional[float] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    ReachedOnError: Optional[float] = None
    Runs: Optional[float] = None
    RunsBattedIn: Optional[float] = None
    SacrificeFlies: Optional[float] = None
    Sacrifices: Optional[float] = None
    Saves: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Singles: Optional[float] = None
    SluggingPercentage: Optional[float] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    StolenBases: Optional[float] = None
    Strikeouts: Optional[float] = None
    SubstituteBattingOrder: Optional[int] = None
    SubstituteBattingOrderSequence: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    TotalBases: Optional[float] = None
    TotalOutsPitched: Optional[float] = None
    Triples: Optional[float] = None
    Updated: Optional[str] = None
    Walks: Optional[float] = None
    WalksHitsPerInningsPitched: Optional[float] = None
    WeightedOnBasePercentage: Optional[float] = None
    Wins: Optional[float] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None


class PlayerSeason(BaseModel):
    AtBats: Optional[float] = None
    AuctionValue: Optional[int] = None
    AverageDraftPosition: Optional[float] = None
    BallsInPlay: Optional[float] = None
    BattingAverage: Optional[float] = None
    BattingAverageOnBallsInPlay: Optional[float] = None
    BattingOrder: Optional[int] = None
    BattingOrderConfirmed: Optional[bool] = None
    CaughtStealing: Optional[float] = None
    DoublePlays: Optional[float] = None
    Doubles: Optional[float] = None
    EarnedRunAverage: Optional[float] = None
    Errors: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsBatting: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsPitching: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldingIndependentPitching: Optional[float] = None
    FlyOuts: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    GrandSlams: Optional[float] = None
    GroundIntoDoublePlay: Optional[float] = None
    GroundOuts: Optional[float] = None
    HitByPitch: Optional[float] = None
    Hits: Optional[float] = None
    HomeRuns: Optional[float] = None
    InningsPitchedDecimal: Optional[float] = None
    InningsPitchedFull: Optional[float] = None
    InningsPitchedOuts: Optional[float] = None
    IntentionalWalks: Optional[float] = None
    IsolatedPower: Optional[float] = None
    LeftOnBase: Optional[float] = None
    LineOuts: Optional[float] = None
    Losses: Optional[float] = None
    Name: Optional[str] = None
    OnBasePercentage: Optional[float] = None
    OnBasePlusSlugging: Optional[float] = None
    Outs: Optional[float] = None
    PitchesSeen: Optional[float] = None
    PitchesThrown: Optional[float] = None
    PitchesThrownStrikes: Optional[float] = None
    PitchingBallsInPlay: Optional[float] = None
    PitchingBattingAverageAgainst: Optional[float] = None
    PitchingBattingAverageOnBallsInPlay: Optional[float] = None
    PitchingBlownSaves: Optional[float] = None
    PitchingCatchersInterference: Optional[float] = None
    PitchingCompleteGames: Optional[float] = None
    PitchingDoublePlays: Optional[float] = None
    PitchingDoubles: Optional[float] = None
    PitchingEarnedRuns: Optional[float] = None
    PitchingFlyOuts: Optional[float] = None
    PitchingGrandSlams: Optional[float] = None
    PitchingGroundIntoDoublePlay: Optional[float] = None
    PitchingGroundOuts: Optional[float] = None
    PitchingHitByPitch: Optional[float] = None
    PitchingHits: Optional[float] = None
    PitchingHolds: Optional[float] = None
    PitchingHomeRuns: Optional[float] = None
    PitchingInningStarted: Optional[int] = None
    PitchingIntentionalWalks: Optional[float] = None
    PitchingLineOuts: Optional[float] = None
    PitchingNoHitters: Optional[float] = None
    PitchingOnBasePercentage: Optional[float] = None
    PitchingOnBasePlusSlugging: Optional[float] = None
    PitchingPerfectGames: Optional[float] = None
    PitchingPlateAppearances: Optional[float] = None
    PitchingPopOuts: Optional[float] = None
    PitchingQualityStarts: Optional[float] = None
    PitchingReachedOnError: Optional[float] = None
    PitchingRuns: Optional[float] = None
    PitchingSacrificeFlies: Optional[float] = None
    PitchingSacrifices: Optional[float] = None
    PitchingShutOuts: Optional[float] = None
    PitchingSingles: Optional[float] = None
    PitchingSluggingPercentage: Optional[float] = None
    PitchingStrikeouts: Optional[float] = None
    PitchingStrikeoutsPerNineInnings: Optional[float] = None
    PitchingTotalBases: Optional[float] = None
    PitchingTriples: Optional[float] = None
    PitchingWalks: Optional[float] = None
    PitchingWalksPerNineInnings: Optional[float] = None
    PitchingWeightedOnBasePercentage: Optional[float] = None
    PlateAppearances: Optional[float] = None
    PlayerID: Optional[int] = None
    PopOuts: Optional[float] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    ReachedOnError: Optional[float] = None
    Runs: Optional[float] = None
    RunsBattedIn: Optional[float] = None
    SacrificeFlies: Optional[float] = None
    Sacrifices: Optional[float] = None
    Saves: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Singles: Optional[float] = None
    SluggingPercentage: Optional[float] = None
    Started: Optional[int] = None
    StatID: Optional[int] = None
    StolenBases: Optional[float] = None
    Strikeouts: Optional[float] = None
    SubstituteBattingOrder: Optional[int] = None
    SubstituteBattingOrderSequence: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    TotalBases: Optional[float] = None
    TotalOutsPitched: Optional[float] = None
    Triples: Optional[float] = None
    Updated: Optional[str] = None
    Walks: Optional[float] = None
    WalksHitsPerInningsPitched: Optional[float] = None
    WeightedOnBasePercentage: Optional[float] = None
    Wins: Optional[float] = None


class Season(BaseModel):
    ApiSeason: Optional[str] = None
    PostSeasonStartDate: Optional[str] = None
    RegularSeasonStartDate: Optional[str] = None
    Season: Optional[int] = None
    SeasonType: Optional[str] = None


class Series(BaseModel):
    AwayTeamWins: Optional[int] = None
    GameNumber: Optional[int] = None
    HomeTeamWins: Optional[int] = None
    MaxLength: Optional[int] = None


class Stadium(BaseModel):
    Active: Optional[bool] = None
    Altitude: Optional[int] = None
    Capacity: Optional[int] = None
    CenterField: Optional[int] = None
    City: Optional[str] = None
    Country: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    HomePlateDirection: Optional[int] = None
    LeftCenterField: Optional[int] = None
    LeftField: Optional[int] = None
    MidLeftCenterField: Optional[int] = None
    MidLeftField: Optional[int] = None
    MidRightCenterField: Optional[int] = None
    MidRightField: Optional[int] = None
    Name: Optional[str] = None
    RightCenterField: Optional[int] = None
    RightField: Optional[int] = None
    StadiumID: Optional[int] = None
    State: Optional[str] = None
    Surface: Optional[str] = None
    Type: Optional[str] = None


class Standing(BaseModel):
    AwayLosses: Optional[int] = None
    AwayWins: Optional[int] = None
    City: Optional[str] = None
    DayLosses: Optional[int] = None
    DayWins: Optional[int] = None
    Division: Optional[str] = None
    DivisionLosses: Optional[int] = None
    DivisionRank: Optional[int] = None
    DivisionWins: Optional[int] = None
    GamesBehind: Optional[float] = None
    GlobalTeamID: Optional[int] = None
    HomeLosses: Optional[int] = None
    HomeWins: Optional[int] = None
    Key: Optional[str] = None
    LastTenGamesLosses: Optional[int] = None
    LastTenGamesWins: Optional[int] = None
    League: Optional[str] = None
    LeagueRank: Optional[int] = None
    Losses: Optional[int] = None
    Name: Optional[str] = None
    NightLosses: Optional[int] = None
    NightWins: Optional[int] = None
    Percentage: Optional[float] = None
    RunsAgainst: Optional[int] = None
    RunsScored: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Streak: Optional[str] = None
    TeamID: Optional[int] = None
    WildCardGamesBehind: Optional[float] = None
    WildCardRank: Optional[int] = None
    Wins: Optional[int] = None


class Team(BaseModel):
    Active: Optional[bool] = None
    City: Optional[str] = None
    Division: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Key: Optional[str] = None
    League: Optional[str] = None
    Name: Optional[str] = None
    PrimaryColor: Optional[str] = None
    QuaternaryColor: Optional[str] = None
    SecondaryColor: Optional[str] = None
    StadiumID: Optional[int] = None
    TeamID: Optional[int] = None
    TertiaryColor: Optional[str] = None
    WikipediaLogoUrl: Optional[str] = None
    WikipediaWordMarkUrl: Optional[str] = None


class TeamGame(BaseModel):
    AtBats: Optional[float] = None
    BallsInPlay: Optional[float] = None
    BattingAverage: Optional[float] = None
    BattingAverageOnBallsInPlay: Optional[float] = None
    BattingOrderConfirmed: Optional[bool] = None
    CaughtStealing: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DoublePlays: Optional[float] = None
    Doubles: Optional[float] = None
    EarnedRunAverage: Optional[float] = None
    Errors: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsBatting: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsPitching: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldingIndependentPitching: Optional[float] = None
    FlyOuts: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    GrandSlams: Optional[float] = None
    GroundIntoDoublePlay: Optional[float] = None
    GroundOuts: Optional[float] = None
    HitByPitch: Optional[float] = None
    Hits: Optional[float] = None
    HomeOrAway: Optional[str] = None
    HomeRuns: Optional[float] = None
    InningsPitchedDecimal: Optional[float] = None
    InningsPitchedFull: Optional[float] = None
    InningsPitchedOuts: Optional[float] = None
    IntentionalWalks: Optional[float] = None
    IsGameOver: Optional[bool] = None
    IsolatedPower: Optional[float] = None
    LeftOnBase: Optional[float] = None
    LineOuts: Optional[float] = None
    Losses: Optional[float] = None
    Name: Optional[str] = None
    OnBasePercentage: Optional[float] = None
    OnBasePlusSlugging: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    Outs: Optional[float] = None
    PitchesSeen: Optional[float] = None
    PitchesThrown: Optional[float] = None
    PitchesThrownStrikes: Optional[float] = None
    PitchingBallsInPlay: Optional[float] = None
    PitchingBattingAverageAgainst: Optional[float] = None
    PitchingBattingAverageOnBallsInPlay: Optional[float] = None
    PitchingBlownSaves: Optional[float] = None
    PitchingCatchersInterference: Optional[float] = None
    PitchingCompleteGames: Optional[float] = None
    PitchingDoublePlays: Optional[float] = None
    PitchingDoubles: Optional[float] = None
    PitchingEarnedRuns: Optional[float] = None
    PitchingFlyOuts: Optional[float] = None
    PitchingGrandSlams: Optional[float] = None
    PitchingGroundIntoDoublePlay: Optional[float] = None
    PitchingGroundOuts: Optional[float] = None
    PitchingHitByPitch: Optional[float] = None
    PitchingHits: Optional[float] = None
    PitchingHolds: Optional[float] = None
    PitchingHomeRuns: Optional[float] = None
    PitchingInningStarted: Optional[int] = None
    PitchingIntentionalWalks: Optional[float] = None
    PitchingLineOuts: Optional[float] = None
    PitchingNoHitters: Optional[float] = None
    PitchingOnBasePercentage: Optional[float] = None
    PitchingOnBasePlusSlugging: Optional[float] = None
    PitchingPerfectGames: Optional[float] = None
    PitchingPlateAppearances: Optional[float] = None
    PitchingPopOuts: Optional[float] = None
    PitchingQualityStarts: Optional[float] = None
    PitchingReachedOnError: Optional[float] = None
    PitchingRuns: Optional[float] = None
    PitchingSacrificeFlies: Optional[float] = None
    PitchingSacrifices: Optional[float] = None
    PitchingShutOuts: Optional[float] = None
    PitchingSingles: Optional[float] = None
    PitchingSluggingPercentage: Optional[float] = None
    PitchingStrikeouts: Optional[float] = None
    PitchingStrikeoutsPerNineInnings: Optional[float] = None
    PitchingTotalBases: Optional[float] = None
    PitchingTriples: Optional[float] = None
    PitchingWalks: Optional[float] = None
    PitchingWalksPerNineInnings: Optional[float] = None
    PitchingWeightedOnBasePercentage: Optional[float] = None
    PlateAppearances: Optional[float] = None
    PopOuts: Optional[float] = None
    ReachedOnError: Optional[float] = None
    Runs: Optional[float] = None
    RunsBattedIn: Optional[float] = None
    SacrificeFlies: Optional[float] = None
    Sacrifices: Optional[float] = None
    Saves: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Singles: Optional[float] = None
    SluggingPercentage: Optional[float] = None
    StatID: Optional[int] = None
    StolenBases: Optional[float] = None
    Strikeouts: Optional[float] = None
    SubstituteBattingOrder: Optional[int] = None
    SubstituteBattingOrderSequence: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    TotalBases: Optional[float] = None
    TotalOutsPitched: Optional[float] = None
    Triples: Optional[float] = None
    Updated: Optional[str] = None
    Walks: Optional[float] = None
    WalksHitsPerInningsPitched: Optional[float] = None
    WeightedOnBasePercentage: Optional[float] = None
    Wins: Optional[float] = None


class TeamSeason(BaseModel):
    AtBats: Optional[float] = None
    BallsInPlay: Optional[float] = None
    BattingAverage: Optional[float] = None
    BattingAverageOnBallsInPlay: Optional[float] = None
    BattingOrderConfirmed: Optional[bool] = None
    CaughtStealing: Optional[float] = None
    DoublePlays: Optional[float] = None
    Doubles: Optional[float] = None
    EarnedRunAverage: Optional[float] = None
    Errors: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsBatting: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsPitching: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldingIndependentPitching: Optional[float] = None
    FlyOuts: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    GrandSlams: Optional[float] = None
    GroundIntoDoublePlay: Optional[float] = None
    GroundOuts: Optional[float] = None
    HitByPitch: Optional[float] = None
    Hits: Optional[float] = None
    HomeRuns: Optional[float] = None
    InningsPitchedDecimal: Optional[float] = None
    InningsPitchedFull: Optional[float] = None
    InningsPitchedOuts: Optional[float] = None
    IntentionalWalks: Optional[float] = None
    IsolatedPower: Optional[float] = None
    LeftOnBase: Optional[float] = None
    LineOuts: Optional[float] = None
    Losses: Optional[float] = None
    Name: Optional[str] = None
    OnBasePercentage: Optional[float] = None
    OnBasePlusSlugging: Optional[float] = None
    Outs: Optional[float] = None
    PitchesSeen: Optional[float] = None
    PitchesThrown: Optional[float] = None
    PitchesThrownStrikes: Optional[float] = None
    PitchingBallsInPlay: Optional[float] = None
    PitchingBattingAverageAgainst: Optional[float] = None
    PitchingBattingAverageOnBallsInPlay: Optional[float] = None
    PitchingBlownSaves: Optional[float] = None
    PitchingCatchersInterference: Optional[float] = None
    PitchingCompleteGames: Optional[float] = None
    PitchingDoublePlays: Optional[float] = None
    PitchingDoubles: Optional[float] = None
    PitchingEarnedRuns: Optional[float] = None
    PitchingFlyOuts: Optional[float] = None
    PitchingGrandSlams: Optional[float] = None
    PitchingGroundIntoDoublePlay: Optional[float] = None
    PitchingGroundOuts: Optional[float] = None
    PitchingHitByPitch: Optional[float] = None
    PitchingHits: Optional[float] = None
    PitchingHolds: Optional[float] = None
    PitchingHomeRuns: Optional[float] = None
    PitchingInningStarted: Optional[int] = None
    PitchingIntentionalWalks: Optional[float] = None
    PitchingLineOuts: Optional[float] = None
    PitchingNoHitters: Optional[float] = None
    PitchingOnBasePercentage: Optional[float] = None
    PitchingOnBasePlusSlugging: Optional[float] = None
    PitchingPerfectGames: Optional[float] = None
    PitchingPlateAppearances: Optional[float] = None
    PitchingPopOuts: Optional[float] = None
    PitchingQualityStarts: Optional[float] = None
    PitchingReachedOnError: Optional[float] = None
    PitchingRuns: Optional[float] = None
    PitchingSacrificeFlies: Optional[float] = None
    PitchingSacrifices: Optional[float] = None
    PitchingShutOuts: Optional[float] = None
    PitchingSingles: Optional[float] = None
    PitchingSluggingPercentage: Optional[float] = None
    PitchingStrikeouts: Optional[float] = None
    PitchingStrikeoutsPerNineInnings: Optional[float] = None
    PitchingTotalBases: Optional[float] = None
    PitchingTriples: Optional[float] = None
    PitchingWalks: Optional[float] = None
    PitchingWalksPerNineInnings: Optional[float] = None
    PitchingWeightedOnBasePercentage: Optional[float] = None
    PlateAppearances: Optional[float] = None
    PopOuts: Optional[float] = None
    ReachedOnError: Optional[float] = None
    Runs: Optional[float] = None
    RunsBattedIn: Optional[float] = None
    SacrificeFlies: Optional[float] = None
    Sacrifices: Optional[float] = None
    Saves: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Singles: Optional[float] = None
    SluggingPercentage: Optional[float] = None
    StatID: Optional[int] = None
    StolenBases: Optional[float] = None
    Strikeouts: Optional[float] = None
    SubstituteBattingOrder: Optional[int] = None
    SubstituteBattingOrderSequence: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    TotalBases: Optional[float] = None
    TotalOutsPitched: Optional[float] = None
    Triples: Optional[float] = None
    Updated: Optional[str] = None
    Walks: Optional[float] = None
    WalksHitsPerInningsPitched: Optional[float] = None
    WeightedOnBasePercentage: Optional[float] = None
    Wins: Optional[float] = None


class FieldFormatAllTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatFreeAgentsGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatHitterVsPitcherHitteridPitcheridGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class FieldFormatNewsGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByDateDateGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByPlayerIDPlayeridGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatPlayerGameStatsByDateDateGetResponse(RootModel[List[PlayerGame]]):
    root: List[PlayerGame]


class FieldFormatPlayerGameStatsBySeasonSeasonPlayeridNumberofgamesGetResponse(
    RootModel[List[PlayerGame]]
):
    root: List[PlayerGame]


class Format17(Enum):
    JSON = 'JSON'
    XML = 'XML'


class FieldFormatPlayerSeasonAwayStatsSeasonGetResponse(RootModel[List[PlayerSeason]]):
    root: List[PlayerSeason]


class Format18(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatPlayerSeasonHomeStatsSeasonGetResponse(RootModel[List[PlayerSeason]]):
    root: List[PlayerSeason]


class FieldFormatPlayerSeasonSplitStatsSeasonSplitGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class Split(Enum):
    L = 'L'
    R = 'R'
    S = 'S'


class FieldFormatPlayerSeasonStatsSeasonGetResponse(RootModel[List[PlayerSeason]]):
    root: List[PlayerSeason]


class FieldFormatPlayerSeasonStatsByTeamSeasonTeamGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class FieldFormatPlayerSeasonStatsSplitByTeamSeasonGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class FieldFormatPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatPlayersTeamGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatStadiumsGetResponse(RootModel[List[Stadium]]):
    root: List[Stadium]


class Format27(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatStandingsSeasonGetResponse(RootModel[List[Standing]]):
    root: List[Standing]


class Format28(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatTeamGameStatsByDateDateGetResponse(RootModel[List[TeamGame]]):
    root: List[TeamGame]


class FieldFormatTeamGameStatsBySeasonSeasonTeamidNumberofgamesGetResponse(
    RootModel[List[TeamGame]]
):
    root: List[TeamGame]


class Format30(Enum):
    JSON = 'JSON'
    XML = 'XML'


class FieldFormatTeamHittersVsPitcherGameidTeamGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class Format31(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatTeamSeasonStatsSeasonGetResponse(RootModel[List[TeamSeason]]):
    root: List[TeamSeason]


class FieldFormatTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class Game(BaseModel):
    Attendance: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamErrors: Optional[int] = None
    AwayTeamHits: Optional[int] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamProbablePitcherID: Optional[int] = None
    AwayTeamRuns: Optional[int] = None
    AwayTeamStartingPitcher: Optional[str] = None
    AwayTeamStartingPitcherID: Optional[int] = None
    Balls: Optional[int] = None
    Channel: Optional[str] = None
    CurrentHitter: Optional[str] = None
    CurrentHitterID: Optional[int] = None
    CurrentHittingTeamID: Optional[int] = None
    CurrentPitcher: Optional[str] = None
    CurrentPitcherID: Optional[int] = None
    CurrentPitchingTeamID: Optional[int] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    DueUpHitterID1: Optional[int] = None
    DueUpHitterID2: Optional[int] = None
    DueUpHitterID3: Optional[int] = None
    ForecastDescription: Optional[str] = None
    ForecastTempHigh: Optional[int] = None
    ForecastTempLow: Optional[int] = None
    ForecastWindChill: Optional[int] = None
    ForecastWindDirection: Optional[int] = None
    ForecastWindSpeed: Optional[int] = None
    GameEndDateTime: Optional[str] = None
    GameID: Optional[int] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeRotationNumber: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamErrors: Optional[int] = None
    HomeTeamHits: Optional[int] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamProbablePitcherID: Optional[int] = None
    HomeTeamRuns: Optional[int] = None
    HomeTeamStartingPitcher: Optional[str] = None
    HomeTeamStartingPitcherID: Optional[int] = None
    Inning: Optional[int] = None
    InningDescription: Optional[str] = None
    InningHalf: Optional[str] = None
    Innings: Optional[List[Inning]] = None
    IsClosed: Optional[bool] = None
    LastPlay: Optional[str] = None
    LosingPitcher: Optional[str] = None
    LosingPitcherID: Optional[int] = None
    NeutralVenue: Optional[bool] = None
    Outs: Optional[int] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    PointSpread: Optional[float] = None
    PointSpreadAwayTeamMoneyLine: Optional[int] = None
    PointSpreadHomeTeamMoneyLine: Optional[int] = None
    RescheduledFromGameID: Optional[int] = None
    RescheduledGameID: Optional[int] = None
    RunnerOnFirst: Optional[bool] = None
    RunnerOnSecond: Optional[bool] = None
    RunnerOnThird: Optional[bool] = None
    SavingPitcher: Optional[str] = None
    SavingPitcherID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SeriesInfo: Optional[Series] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    Strikes: Optional[int] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None
    WinningPitcher: Optional[str] = None
    WinningPitcherID: Optional[int] = None


class FieldFormatGamesSeasonGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatGamesByDateDateGetResponse(RootModel[List[Game]]):
    root: List[Game]


class BoxScore(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    Innings: Optional[List[Inning]] = None
    PlayerGames: Optional[List[PlayerGame]] = None
    TeamGames: Optional[List[TeamGame]] = None


class DfsSlateGame(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    GameID: Optional[int] = None
    OperatorGameID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None


class FieldFormatBoxScoresDateGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class FieldFormatBoxScoresDeltaDateMinutesGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class DfsSlate(BaseModel):
    DfsSlateGames: Optional[List[DfsSlateGame]] = None
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfGames: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SalaryCap: Optional[int] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None


class FieldFormatDfsSlatesByDateDateGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]
